In [4]:
import numpy as np
import pandas as pd

# About Project <br>
1. This is content based recommendation system

# Preparing data

In [5]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [6]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [7]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [8]:
credits.head(1)['cast'].values

array(['[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'],
      dtype=object)

In [9]:
movies.shape

(4803, 20)

In [10]:
credits.shape

(4803, 4)

In [11]:
movies.merge(credits, on='title').shape

(4809, 23)

In [12]:
movies = movies.merge(credits, on='title')

In [13]:
movies.sample()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
1626,0,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""n...",NaN,53113,"[{""id"": 10041, ""name"": ""dysfunctional family""}...",en,One True Thing,A career woman reassesses her parents' lives a...,2.644427,"[{""name"": ""Universal Pictures"", ""id"": 33}]",...,127.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Love What You Have.,One True Thing,6.2,27,53113,"[{""cast_id"": 1, ""character"": ""Kate Gulden"", ""c...","[{""credit_id"": ""52fe4853c3a36847f8161c1d"", ""de..."

In [14]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

# Keeping only required features

In [15]:
# required columns: genres, id, keywords, title, overview, cast, crew
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]
movies.sample()

,movie_id,title,overview,genres,keywords,cast,crew
1488,7220,The Punisher,When undercover FBI agent Frank Castle's wife ...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 473, ""name"": ""chain""}, {""id"": 1375, ""n...","[{""cast_id"": 1, ""character"": ""Frank Castle / T...","[{""credit_id"": ""52fe4474c3a36847f8096fb1"", ""de..."

In [16]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [17]:
movies.dropna(inplace=True)

In [18]:
movies.duplicated().sum()

np.int64(0)

# Preparing Genres

In [19]:
print(type(movies.iloc[0]['genres']))
# The list of genres is a string that needs to be converted to a python list to access its elements
import ast
ast.literal_eval(movies.iloc[0]['genres'])

<class 'str'>

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [20]:
import ast
def convert_str_to_list(obj):
  new_list = []
  for i in ast.literal_eval(obj):
      new_list.append(i['name'])
  return new_list

In [21]:
# convert_to_list(movies.iloc[0]['genres'])
movies['genres'] = movies['genres'].apply(convert_str_to_list)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

# Preparing Keywords

In [22]:
movies['keywords'] = movies['keywords'].apply(convert_str_to_list)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

# Preparing Cast

In [23]:
ast.literal_eval(movies['cast'][0])[0]

{'cast_id': 242,
 'character': 'Jake Sully',
 'credit_id': '5602a8a7c3a3685532001c9a',
 'gender': 2,
 'id': 65731,
 'name': 'Sam Worthington',
 'order': 0}

In [24]:
def convert_cast(obj):
  new_list = []
  count = 0
  for i in ast.literal_eval(obj):
    new_list.append(i['name'])
    count+=1
    if count == 3:
      break
  
  return new_list

In [25]:
movies['cast'] = movies['cast'].apply(convert_cast)
movies.sample(2)

,movie_id,title,overview,genres,keywords,cast,crew
1978,10208,Muppets from Space,When Gonzo's breakfast cereal tells him that h...,"[Fantasy, Comedy, Science Fiction, Family]","[puppet, the muppets]","[Steve Whitmire, Dave Goelz, Bill Barretta]","[{""credit_id"": ""52fe43429251416c75009913"", ""de..."
4093,80,Before Sunset,Nine years ago two strangers met by chance and...,"[Drama, Romance]","[paris, journalist, dialogue, talking, soulmat...","[Ethan Hawke, Julie Delpy, Vernon Dobtcheff]","[{""credit_id"": ""52fe4214c3a36847f8002749"", ""de..."

# Preparing Crew

In [26]:
ast.literal_eval(movies['crew'][0])

[{'credit_id': '52fe48009251416c750aca23',
  'department': 'Editing',
  'gender': 0,
  'id': 1721,
  'job': 'Editor',
  'name': 'Stephen E. Rivkin'},
 {'credit_id': '539c47ecc3a36810e3001f87',
  'department': 'Art',
  'gender': 2,
  'id': 496,
  'job': 'Production Design',
  'name': 'Rick Carter'},
 {'credit_id': '54491c89c3a3680fb4001cf7',
  'department': 'Sound',
  'gender': 0,
  'id': 900,
  'job': 'Sound Designer',
  'name': 'Christopher Boyes'},
 {'credit_id': '54491cb70e0a267480001bd0',
  'department': 'Sound',
  'gender': 0,
  'id': 900,
  'job': 'Supervising Sound Editor',
  'name': 'Christopher Boyes'},
 {'credit_id': '539c4a4cc3a36810c9002101',
  'department': 'Production',
  'gender': 1,
  'id': 1262,
  'job': 'Casting',
  'name': 'Mali Finn'},
 {'credit_id': '5544ee3b925141499f0008fc',
  'department': 'Sound',
  'gender': 2,
  'id': 1729,
  'job': 'Original Music Composer',
  'name': 'James Horner'},
 {'credit_id': '52fe48009251416c750ac9c3',
  'department': 'Directing',
  'gender': 2,
  'id': 2710,
  'job': 'Director',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750ac9d9',
  'department': 'Writing',
  'gender': 2,
  'id': 2710,
  'job': 'Writer',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750aca17',
  'department': 'Editing',
  'gender': 2,
  'id': 2710,
  'job': 'Editor',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750aca29',
  'department': 'Production',
  'gender': 2,
  'id': 2710,
  'job': 'Producer',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750aca3f',
  'department': 'Writing',
  'gender': 2,
  'id': 2710,
  'job': 'Screenplay',
  'name': 'James Cameron'},
 {'credit_id': '539c4987c3a36810ba0021a4',
  'department': 'Art',
  'gender': 2,
  'id': 7236,
  'job': 'Art Direction',
  'name': 'Andrew Menzies'},
 {'credit_id': '549598c3c3a3686ae9004383',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 6690,
  'job': 'Visual Effects Producer',
  'name': 'Jill Brooks'},
 {'credit_id': '52fe48009251416c750aca4b',
  'department': 'Production',
  'gender': 1,
  'id': 6347,
  'job': 'Casting',
  'name': 'Margery Simkin'},
 {'credit_id': '570b6f419251417da70032fe',
  'department': 'Art',
  'gender': 2,
  'id': 6878,
  'job': 'Supervising Art Director',
  'name': 'Kevin Ishioka'},
 {'credit_id': '5495a0fac3a3686ae9004468',
  'department': 'Sound',
  'gender': 0,
  'id': 6883,
  'job': 'Music Editor',
  'name': 'Dick Bernstein'},
 {'credit_id': '54959706c3a3686af3003e81',
  'department': 'Sound',
  'gender': 0,
  'id': 8159,
  'job': 'Sound Effects Editor',
  'name': 'Shannon Mills'},
 {'credit_id': '54491d58c3a3680fb1001ccb',
  'department': 'Sound',
  'gender': 0,
  'id': 8160,
  'job': 'Foley',
  'name': 'Dennie Thorpe'},
 {'credit_id': '54491d6cc3a3680fa5001b2c',
  'department': 'Sound',
  'gender': 0,
  'id': 8163,
  'job': 'Foley',
  'name': 'Jana Vance'},
 {'credit_id': '52fe48009251416c750aca57',
  'department': 'Costume & Make-Up',
  'gender': 1,
  'id': 8527,
  'job': 'Costume Design',
  'name': 'Deborah Lynn Scott'},
 {'credit_id': '52fe48009251416c750aca2f',
  'department': 'Production',
  'gender': 2,
  'id': 8529,
  'job': 'Producer',
  'name': 'Jon Landau'},
 {'credit_id': '539c4937c3a36810ba002194',
  'department': 'Art',
  'gender': 0,
  'id': 9618,
  'job': 'Art Direction',
  'name': 'Sean Haworth'},
 {'credit_id': '539c49b6c3a36810c10020e6',
  'department': 'Art',
  'gender': 1,
  'id': 12653,
  'job': 'Set Decoration',
  'name': 'Kim Sinclair'},
 {'credit_id': '570b6f2f9251413a0e00020d',
  'department': 'Art',
  'gender': 1,
  'id': 12653,
  'job': 'Supervising Art Director',
  'name': 'Kim Sinclair'},
 {'credit_id': '54491a6c0e0a26748c001b19',
  'department': 'Art',
  'gender': 2,
  'id': 14350,
  'job': 'Set Designer',
  'name': 'Richard F. Mays'},
 {'credit_id': '56928cf4c3a3684cff0025c4',
  'department': 'Production',
  'gender': 1,
  'id': 20294,
  'job': 'Executive Producer',
  'name': 'Laeta Kalogridis'},
 {'credit_id': '52fe48009251416c750aca51',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 17675,
  'job': 'Costume Design',
  'name': 'Mayes C. Rubeo'},
 {'credit_id': '52fe48009251416c750aca11',
  'department': 'Camera',
  'gender': 2,
  'id': 18265,
  'job': 'Director of Photography',
  'name': 'Mauro Fiore'},
 {'credit_id': '5449194d0e0a26748f001b39',
  'department': 'Art',
  'gender': 0,
  'id': 42281,
  'job': 'Set Designer',
  'name': 'Scott Herbertson'},
 {'credit_id': '52fe48009251416c750aca05',
  'department': 'Crew',
  'gender': 0,
  'id': 42288,
  'job': 'Stunts',
  'name': 'Woody Schultz'},
 {'credit_id': '5592aefb92514152de0010f5',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 29067,
  'job': 'Makeup Artist',
  'name': 'Linda DeVetta'},
 {'credit_id': '5592afa492514152de00112c',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 29067,
  'job': 'Hairstylist',
  'name': 'Linda DeVetta'},
 {'credit_id': '54959ed592514130fc002e5d',
  'department': 'Camera',
  'gender': 2,
  'id': 33302,
  'job': 'Camera Operator',
  'name': 'Richard Bluck'},
 {'credit_id': '539c4891c3a36810ba002147',
  'department': 'Art',
  'gender': 2,
  'id': 33303,
  'job': 'Art Direction',
  'name': 'Simon Bright'},
 {'credit_id': '54959c069251417a81001f3a',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 113145,
  'job': 'Visual Effects Supervisor',
  'name': 'Richard Martin'},
 {'credit_id': '54959a0dc3a3680ff5002c8d',
  'department': 'Crew',
  'gender': 2,
  'id': 58188,
  'job': 'Visual Effects Editor',
  'name': 'Steve R. Moore'},
 {'credit_id': '52fe48009251416c750aca1d',
  'department': 'Editing',
  'gender': 2,
  'id': 58871,
  'job': 'Editor',
  'name': 'John Refoua'},
 {'credit_id': '54491a4dc3a3680fc30018ca',
  'department': 'Art',
  'gender': 0,
  'id': 92359,
  'job': 'Set Designer',
  'name': 'Karl J. Martin'},
 {'credit_id': '52fe48009251416c750aca35',
  'department': 'Camera',
  'gender': 1,
  'id': 72201,
  'job': 'Director of Photography',
  'name': 'Chiling Lin'},
 {'credit_id': '52fe48009251416c750ac9ff',
  'department': 'Crew',
  'gender': 0,
  'id': 89714,
  'job': 'Stunts',
  'name': 'Ilram Choi'},
 {'credit_id': '54959c529251416e2b004394',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 93214,
  'job': 'Visual Effects Supervisor',
  'name': 'Steven Quale'},
 {'credit_id': '54491edf0e0a267489001c37',
  'department': 'Crew',
  'gender': 1,
  'id': 122607,
  'job': 'Dialect Coach',
  'name': 'Carla Meyer'},
 {'credit_id': '539c485bc3a368653d001a3a',
  'department': 'Art',
  'gender': 2,
  'id': 132585,
  'job': 'Art Direction',
  'name': 'Nick Bassett'},
 {'credit_id': '539c4903c3a368653d001a74',
  'department': 'Art',
  'gender': 0,
  'id': 132596,
  'job': 'Art Direction',
  'name': 'Jill Cormack'},
 {'credit_id': '539c4967c3a368653d001a94',
  'department': 'Art',
  'gender': 0,
  'id': 132604,
  'job': 'Art Direction',
  'name': 'Andy McLaren'},
 {'credit_id': '52fe48009251416c750aca45',
  'department': 'Crew',
  'gender': 0,
  'id': 236696,
  'job': 'Motion Capture Artist',
  'name': 'Terry Notary'},
 {'credit_id': '54959e02c3a3680fc60027d2',
  'department': 'Crew',
  'gender': 2,
  'id': 956198,
  'job': 'Stunt Coordinator',
  'name': 'Garrett Warren'},
 {'credit_id': '54959ca3c3a3686ae300438c',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 957874,
  'job': 'Visual Effects Supervisor',
  'name': 'Jonathan Rothbart'},
 {'credit_id': '570b6f519251412c74001b2f',
  'department': 'Art',
  'gender': 0,
  'id': 957889,
  'job': 'Supervising Art Director',
  'name': 'Stefan Dechant'},
 {'credit_id': '570b6f62c3a3680b77007460',
  'department': 'Art',
  'gender': 2,
  'id': 959555,
  'job': 'Supervising Art Director',
  'name': 'Todd Cherniawsky'},
 {'credit_id': '539c4a3ac3a36810da0021cc',
  'department': 'Production',
  'gender': 0,
  'id': 1016177,
  'job': 'Casting',
  'name': 'Miranda Rivers'},
 {'credit_id': '539c482cc3a36810c1002062',
  'department': 'Art',
  'gender': 0,
  'id': 1032536,
  'job': 'Production Design',
  'name': 'Robert Stromberg'},
 {'credit_id': '539c4b65c3a36810c9002125',
  'department': 'Costume & Make-Up',
  'gender': 2,
  'id': 1071680,
  'job': 'Costume Design',
  'name': 'John Harding'},
 {'credit_id': '54959e6692514130fc002e4e',
  'department': 'Camera',
  'gender': 0,
  'id': 1177364,
  'job': 'Steadicam Operator',
  'name': 'Roberto De Angelis'},
 {'credit_id': '539c49f1c3a368653d001aac',
  'department': 'Costume & Make-Up',
  'gender': 2,
  'id': 1202850,
  'job': 'Makeup Department Head',
  'name': 'Mike Smithson'},
 {'credit_id': '5495999ec3a3686ae100460c',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1204668,
  'job': 'Visual Effects Producer',
  'name': 'Alain Lalanne'},
 {'credit_id': '54959cdfc3a3681153002729',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1206410,
  'job': 'Visual Effects Supervisor',
  'name': 'Lucas Salton'},
 {'credit_id': '549596239251417a81001eae',
  'department': 'Crew',
  'gender': 0,
  'id': 1234266,
  'job': 'Post Production Supervisor',
  'name': 'Janace Tashjian'},
 {'credit_id': '54959c859251416e1e003efe',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1271932,
  'job': 'Visual Effects Supervisor',
  'name': 'Stephen Rosenbaum'},
 {'credit_id': '5592af28c3a368775a00105f',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1310064,
  'job': 'Makeup Artist',
  'name': 'Frankie Karena'},
 {'credit_id': '539c4adfc3a36810e300203b',
  'department': 'Costume & Make-Up',
  'gender': 1,
  'id': 1319844,
  'job': 'Costume Supervisor',
  'name': 'Lisa Lovaas'},
 {'credit_id': '54959b579251416e2b004371',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1327028,
  'job': 'Visual Effects Supervisor',
  'name': 'Jonathan Fawkner'},
 {'credit_id': '539c48a7c3a36810b5001fa7',
  'department': 'Art',
  'gender': 0,
  'id': 1330561,
  'job': 'Art Direction',
  'name': 'Robert Bavin'},
 {'credit_id': '539c4a71c3a36810da0021e0',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1330567,
  'job': 'Costume Supervisor',
  'name': 'Anthony Almaraz'},
 {'credit_id': '539c4a8ac3a36810ba0021e4',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1330570,
  'job': 'Costume Supervisor',
  'name': 'Carolyn M. Fenton'},
 {'credit_id': '539c4ab6c3a36810da0021f0',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1330574,
  'job': 'Costume Supervisor',
  'name': 'Beth Koenigsberg'},
 {'credit_id': '54491ab70e0a267480001ba2',
  'department': 'Art',
  'gender': 0,
  'id': 1336191,
  'job': 'Set Designer',
  'name': 'Sam Page'},
 {'credit_id': '544919d9c3a3680fc30018bd',
  'department': 'Art',
  'gender': 0,
  'id': 1339441,
  'job': 'Set Designer',
  'name': 'Tex Kadonaga'},
 {'credit_id': '54491cf50e0a267483001b0c',
  'department': 'Editing',
  'gender': 0,
  'id': 1352422,
  'job': 'Dialogue Editor',
  'name': 'Kim Foscato'},
 {'credit_id': '544919f40e0a26748c001b09',
  'department': 'Art',
  'gender': 0,
  'id': 1352962,
  'job': 'Set Designer',
  'name': 'Tammy S. Lee'},
 {'credit_id': '5495a115c3a3680ff5002d71',
  'department': 'Crew',
  'gender': 0,
  'id': 1357070,
  'job': 'Transportation Coordinator',
  'name': 'Denny Caira'},
 {'credit_id': '5495a12f92514130fc002e94',
  'department': 'Crew',
  'gender': 0,
  'id': 1357071,
  'job': 'Transportation Coordinator',
  'name': 'James Waitkus'},
 {'credit_id': '5495976fc3a36811530026b0',
  'department': 'Sound',
  'gender': 0,
  'id': 1360103,
  'job': 'Supervising Sound Editor',
  'name': 'Addison Teague'},
 {'credit_id': '54491837c3a3680fb1001c5a',
  'department': 'Art',
  'gender': 2,
  'id': 1376887,
  'job': 'Set Designer',
  'name': 'C. Scott Baker'},
 {'credit_id': '54491878c3a3680fb4001c9d',
  'department': 'Art',
  'gender': 0,
  'id': 1376888,
  'job': 'Set Designer',
  'name': 'Luke Caska'},
 {'credit_id': '544918dac3a3680fa5001ae0',
  'department': 'Art',
  'gender': 0,
  'id': 1376889,
  'job': 'Set Designer',
  'name': 'David Chow'},
 {'credit_id': '544919110e0a267486001b68',
  'department': 'Art',
  'gender': 0,
  'id': 1376890,
  'job': 'Set Designer',
  'name': 'Jonathan Dyer'},
 {'credit_id': '54491967c3a3680faa001b5e',
  'department': 'Art',
  'gender': 0,
  'id': 1376891,
  'job': 'Set Designer',
  'name': 'Joseph Hiura'},
 {'credit_id': '54491997c3a3680fb1001c8a',
  'department': 'Art',
  'gender': 0,
  'id': 1376892,
  'job': 'Art Department Coordinator',
  'name': 'Rebecca Jellie'},
 {'credit_id': '544919ba0e0a26748f001b42',
  'department': 'Art',
  'gender': 0,
  'id': 1376893,
  'job': 'Set Designer',
  'name': 'Robert Andrew Johnson'},
 {'credit_id': '54491b1dc3a3680faa001b8c',
  'department': 'Art',
  'gender': 0,
  'id': 1376895,
  'job': 'Assistant Art Director',
  'name': 'Mike Stassi'},
 {'credit_id': '54491b79c3a3680fbb001826',
  'department': 'Art',
  'gender': 0,
  'id': 1376897,
  'job': 'Construction Coordinator',
  'name': 'John Villarino'},
 {'credit_id': '54491baec3a3680fb4001ce6',
  'department': 'Art',
  'gender': 2,
  'id': 1376898,
  'job': 'Assistant Art Director',
  'name': 'Jeffrey Wisniewski'},
 {'credit_id': '54491d2fc3a3680fb4001d07',
  'department': 'Editing',
  'gender': 0,
  'id': 1376899,
  'job': 'Dialogue Editor',
  'name': 'Cheryl Nardi'},
 {'credit_id': '54491d86c3a3680fa5001b2f',
  'department': 'Editing',
  'gender': 0,
  'id': 1376901,
  'job': 'Dialogue Editor',
  'name': 'Marshall Winn'},
 {'credit_id': '54491d9dc3a3680faa001bb0',
  'department': 'Sound',
  'gender': 0,
  'id': 1376902,
  'job': 'Supervising Sound Editor',
  'name': 'Gwendolyn Yates Whittle'},
 {'credit_id': '54491dc10e0a267486001bce',
  'department': 'Sound',
  'gender': 0,
  'id': 1376903,
  'job': 'Sound Re-Recording Mixer',
  'name': 'William Stein'},
 {'credit_id': '54491f500e0a26747c001c07',
  'department': 'Crew',
  'gender': 0,
  'id': 1376909,
  'job': 'Choreographer',
  'name': 'Lula Washington'},
 {'credit_id': '549599239251412c4e002a2e',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1391692,
  'job': 'Visual Effects Producer',
  'name': 'Chris Del Conte'},
 {'credit_id': '54959d54c3a36831b8001d9a',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 1391695,
  'job': 'Visual Effects Supervisor',
  'name': 'R. Christopher White'},
 {'credit_id': '54959bdf9251412c4e002a66',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1394070,
  'job': 'Visual Effects Supervisor',
  'name': 'Dan Lemmon'},
 {'credit_id': '5495971d92514132ed002922',
  'department': 'Sound',
  'gender': 0,
  'id': 1394129,
  'job': 'Sound Effects Editor',
  'name': 'Tim Nielsen'},
 {'credit_id': '5592b25792514152cc0011aa',
  'department': 'Crew',
  'gender': 0,
  'id': 1394286,
  'job': 'CG Supervisor',
  'name': 'Michael Mulholland'},
 {'credit_id': '54959a329251416e2b004355',
  'department': 'Crew',
  'gender': 0,
  'id': 1394750,
  'job': 'Visual Effects Editor',
  'name': 'Thomas Nittmann'},
 {'credit_id': '54959d6dc3a3686ae9004401',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1394755,
  'job': 'Visual Effects Supervisor',
  'name': 'Edson Williams'},
 {'credit_id': '5495a08fc3a3686ae300441c',
  'department': 'Editing',
  'gender': 0,
  'id': 1394953,
  'job': 'Digital Intermediate',
  'name': 'Christine Carr'},
 {'credit_id': '55402d659251413d6d000249',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1395269,
  'job': 'Visual Effects Supervisor',
  'name': 'John Bruno'},
 {'credit_id': '54959e7b9251416e1e003f3e',
  'department': 'Camera',
  'gender': 0,
  'id': 1398970,
  'job': 'Steadicam Operator',
  'name': 'David Emmerichs'},
 {'credit_id': '54959734c3a3686ae10045e0',
  'department': 'Sound',
  'gender': 0,
  'id': 1400906,
  'job': 'Sound Effects Editor',
  'name': 'Christopher Scarabosio'},
 {'credit_id': '549595dd92514130fc002d79',
  'department': 'Production',
  'gender': 0,
  'id': 1401784,
  'job': 'Production Supervisor',
  'name': 'Jennifer Teves'},
 {'credit_id': '549596009251413af70028cc',
  'department': 'Production',
  'gender': 0,
  'id': 1401785,
  'job': 'Production Manager',
  'name': 'Brigitte Yorke'},
 {'credit_id': '549596e892514130fc002d99',
  'department': 'Sound',
  'gender': 0,
  'id': 1401786,
  'job': 'Sound Effects Editor',
  'name': 'Ken Fischer'},
 {'credit_id': '549598229251412c4e002a1c',
  'department': 'Crew',
  'gender': 0,
  'id': 1401787,
  'job': 'Special Effects Coordinator',
  'name': 'Iain Hutton'},
 {'credit_id': '549598349251416e2b00432b',
  'department': 'Crew',
  'gender': 0,
  'id': 1401788,
  'job': 'Special Effects Coordinator',
  'name': 'Steve Ingram'},
 {'credit_id': '54959905c3a3686ae3004324',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401789,
  'job': 'Visual Effects Producer',
  'name': 'Joyce Cox'},
 {'credit_id': '5495994b92514132ed002951',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401790,
  'job': 'Visual Effects Producer',
  'name': 'Jenny Foster'},
 {'credit_id': '549599cbc3a3686ae1004613',
  'department': 'Crew',
  'gender': 0,
  'id': 1401791,
  'job': 'Visual Effects Editor',
  'name': 'Christopher Marino'},
 {'credit_id': '549599f2c3a3686ae100461e',
  'department': 'Crew',
  'gender': 0,
  'id': 1401792,
  'job': 'Visual Effects Editor',
  'name': 'Jim Milton'},
 {'credit_id': '54959a51c3a3686af3003eb5',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401793,
  'job': 'Visual Effects Producer',
  'name': 'Cyndi Ochs'},
 {'credit_id': '54959a7cc3a36811530026f4',
  'department': 'Crew',
  'gender': 0,
  'id': 1401794,
  'job': 'Visual Effects Editor',
  'name': 'Lucas Putnam'},
 {'credit_id': '54959b91c3a3680ff5002cb4',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401795,
  'job': 'Visual Effects Supervisor',
  'name': "Anthony 'Max' Ivins"},
 {'credit_id': '54959bb69251412c4e002a5f',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401796,
  'job': 'Visual Effects Supervisor',
  'name': 'John Knoll'},
 {'credit_id': '54959cbbc3a3686ae3004391',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 1401799,
  'job': 'Visual Effects Supervisor',
  'name': 'Eric Saindon'},
 {'credit_id': '54959d06c3a3686ae90043f6',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401800,
  'job': 'Visual Effects Supervisor',
  'name': 'Wayne Stables'},
 {'credit_id': '54959d259251416e1e003f11',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401801,
  'job': 'Visual Effects Supervisor',
  'name': 'David Stinnett'},
 {'credit_id': '54959db49251413af7002975',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401803,
  'job': 'Visual Effects Supervisor',
  'name': 'Guy Williams'},
 {'credit_id': '54959de4c3a3681153002750',
  'department': 'Crew',
  'gender': 0,
  'id': 1401804,
  'job': 'Stunt Coordinator',
  'name': 'Stuart Thorp'},
 {'credit_id': '54959ef2c3a3680fc60027f2',
  'department': 'Lighting',
  'gender': 0,
  'id': 1401805,
  'job': 'Best Boy Electric',
  'name': 'Giles Coburn'},
 {'credit_id': '54959f07c3a3680fc60027f9',
  'department': 'Camera',
  'gender': 2,
  'id': 1401806,
  'job': 'Still Photographer',
  'name': 'Mark Fellman'},
 {'credit_id': '54959f47c3a3681153002774',
  'department': 'Lighting',
  'gender': 0,
  'id': 1401807,
  'job': 'Lighting Technician',
  'name': 'Scott Sprague'},
 {'credit_id': '54959f8cc3a36831b8001df2',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401808,
  'job': 'Animation Director',
  'name': 'Jeremy Hollobon'},
 {'credit_id': '54959fa0c3a36831b8001dfb',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401809,
  'job': 'Animation Director',
  'name': 'Orlando Meunier'},
 {'credit_id': '54959fb6c3a3686af3003f54',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401810,
  'job': 'Animation Director',
  'name': 'Taisuke Tanimura'},
 {'credit_id': '54959fd2c3a36831b8001e02',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1401812,
  'job': 'Set Costumer',
  'name': 'Lilia Mishel Acevedo'},

In [27]:
def fetch_crew(obj):
  new_list = []
  for i in ast.literal_eval(obj):
    if i['job'] == 'Director':
      new_list.append(i['name'])
      break
    
  return new_list

In [28]:
movies['crew'] = movies['crew'].apply(fetch_crew)

In [29]:
movies.sample(3)

,movie_id,title,overview,genres,keywords,cast,crew
748,17610,Year One,When a couple of lazy hunter-gatherers are ban...,"[Comedy, Adventure]","[temple, slavery, stone age, circumcision, heb...","[Jack Black, Michael Cera, Olivia Wilde]",[Harold Ramis]
1685,254470,Pitch Perfect 2,"The Bellas are back, and they are better than ...","[Comedy, Music]","[music, sequel, singer, male female relationsh...","[Anna Kendrick, Rebel Wilson, Hailee Steinfeld]",[Elizabeth Banks]
3453,1725,West Side Story,In the slums of the upper West Side of Manhatt...,"[Crime, Drama, Music]","[slum, street gang, love at first sight, showd...","[Natalie Wood, Richard Beymer, Russ Tamblyn]",[Robert Wise]

# Preparing Overview

In [30]:
movies['overview'] = movies['overview'].apply(lambda x: x.split())

In [31]:
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]

# Removing spaces

In [32]:
def remove_spaces(obj):
  new_list = []
  for i in obj:
    new_list.append(i.replace(' ',''))
  return new_list

In [33]:
movies['genres'] = movies['genres'].apply(remove_spaces)
movies['keywords'] = movies['keywords'].apply(remove_spaces)
movies['cast'] = movies['cast'].apply(remove_spaces)
movies['crew'] = movies['crew'].apply(remove_spaces)
# movies.head(2)

# Creating tags column

In [34]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']
movies['tags'][0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.',
 'Action',
 'Adventure',
 'Fantasy',
 'ScienceFiction',
 'cultureclash',
 'future',
 'spacewar',
 'spacecolony',
 'society',
 'spacetravel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alienplanet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'loveaffair',
 'antiwar',
 'powerrelations',
 'mindandsoul',
 '3d',
 'SamWorthington',
 'ZoeSaldana',
 'SigourneyWeaver',
 'JamesCameron']

In [35]:
new_df = movies[['movie_id','title','tags']]
new_df.head(2)

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."

# Creating a paragraph out of tags list

In [36]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))
new_df['tags'][0]
# new_df.head(2)

C:\Users\Acer1\AppData\Local\Temp\ipykernel_31172\1137699968.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [37]:
new_df['tags'] = new_df['tags'].apply(lambda x : x.lower())
new_df['tags'][0]

C:\Users\Acer1\AppData\Local\Temp\ipykernel_31172\876159925.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x : x.lower())

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

# Text Vectorization

In [41]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')
vectors = cv.fit_transform(new_df['tags']).toarray()
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [42]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

# Stemming

In [43]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
print(ps.stem('leaves'))
print(ps.stem('leaf'))
print(ps.stem('dance'))
print(ps.stem('dancing'))

leav
leaf
danc
danc

In [44]:
ps = PorterStemmer()

In [45]:
def stemming(text):
  y = []
  for i in text.split():
    y.append(ps.stem(i))
  return " ".join(y)

In [46]:
new_df['tags'] = new_df['tags'].apply(stemming)
new_df['tags']

C:\Users\Acer1\AppData\Local\Temp\ipykernel_31172\3748811135.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stemming)

0       in the 22nd century, a parapleg marin is dispa...
1       captain barbossa, long believ to be dead, ha c...
2       a cryptic messag from bond’ past send him on a...
3       follow the death of district attorney harvey d...
4       john carter is a war-weary, former militari ca...
                              ...
4804    el mariachi just want to play hi guitar and ca...
4805    a newlyw couple' honeymoon is upend by the arr...
4806    "signed, sealed, delivered" introduc a dedic q...
4807    when ambiti new york attorney sam is sent to s...
4808    ever sinc the second grade when he first saw h...
Name: tags, Length: 4806, dtype: object

In [47]:
new_df.head(2)

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."

# Calculating similarity between the vectors

In [48]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)
similarity

array([[1.        , 0.08740748, 0.05827165, ..., 0.02418254, 0.02564946,
        0.        ],
       [0.08740748, 1.        , 0.06451613, ..., 0.02677398, 0.        ,
        0.        ],
       [0.05827165, 0.06451613, 1.        , ..., 0.02677398, 0.        ,
        0.        ],
       ...,
       [0.02418254, 0.02677398, 0.02677398, ..., 1.        , 0.07071068,
        0.04836508],
       [0.02564946, 0.        , 0.        , ..., 0.07071068, 1.        ,
        0.05129892],
       [0.        , 0.        , 0.        , ..., 0.04836508, 0.05129892,
        1.        ]])

In [49]:
list(enumerate(similarity[0]))
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x: x[1])

[(0, np.float64(1.0000000000000002)),
 (539, np.float64(0.25038669783359574)),
 (1192, np.float64(0.24779731389167606)),
 (507, np.float64(0.24283093212859141)),
 (260, np.float64(0.2409900932515112)),
 (1214, np.float64(0.23939494881986934)),
 (1916, np.float64(0.233785950059759)),
 (582, np.float64(0.23174488732966075)),
 (1202, np.float64(0.23084512921915967)),
 (2405, np.float64(0.23084512921915967)),
 (3728, np.float64(0.2294157338705618)),
 (1440, np.float64(0.21677749238103003)),
 (322, np.float64(0.21629522817435)),
 (74, np.float64(0.21526419295572297)),
 (3606, np.float64(0.21486752129677)),
 (83, np.float64(0.21296183592613546)),
 (61, np.float64(0.21239769762143662)),
 (4190, np.float64(0.21239769762143662)),
 (1533, np.float64(0.2108663315950723)),
 (2329, np.float64(0.20857039859669468)),
 (47, np.float64(0.20770324619863198)),
 (495, np.float64(0.20751433915982237)),
 (942, np.float64(0.20395079136182276)),
 (972, np.float64(0.20395079136182276)),
 (466, np.float64(0.2029530274475215)),
 (1327, np.float64(0.2029530274475215)),
 (2969, np.float64(0.2024645717996314)),
 (2200, np.float64(0.19767387315371682)),
 (1199, np.float64(0.19466570535691505)),
 (973, np.float64(0.19194297398747862)),
 (151, np.float64(0.19117977822546817)),
 (1273, np.float64(0.19088542889273336)),
 (2782, np.float64(0.19088542889273336)),
 (4046, np.float64(0.18848425873126295)),
 (2997, np.float64(0.18731716231633883)),
 (4405, np.float64(0.18731716231633883)),
 (305, np.float64(0.18541926977182405)),
 (3160, np.float64(0.1853959098637286)),
 (3536, np.float64(0.1842105263157895)),
 (27, np.float64(0.18172434016970185)),
 (3325, np.float64(0.1813690625275029)),
 (150, np.float64(0.1810898182317451)),
 (220, np.float64(0.18074256993863339)),
 (931, np.float64(0.18074256993863339)),
 (300, np.float64(0.17954621161490197)),
 (1069, np.float64(0.17954621161490197)),
 (4, np.float64(0.177343107178349)),
 (36, np.float64(0.177343107178349)),
 (461, np.float64(0.17699808135119718)),
 (1319, np.float64(0.17699808135119718)),
 (184, np.float64(0.17521916101261562)),
 (301, np.float64(0.1745025152241333)),
 (67, np.float64(0.17206180040292132)),
 (46, np.float64(0.16943474841747155)),
 (7, np.float64(0.1692777916923361)),
 (373, np.float64(0.1691275228729346)),
 (1827, np.float64(0.16742770563222897)),
 (2492, np.float64(0.16556654463313053)),
 (2727, np.float64(0.16556654463313053)),
 (149, np.float64(0.16481712868606585)),
 (26, np.float64(0.16452254913212452)),
 (1342, np.float64(0.16452254913212452)),
 (661, np.float64(0.16350382386265752)),
 (208, np.float64(0.16222142113076254)),
 (838, np.float64(0.16222142113076254)),
 (4008, np.float64(0.16222142113076254)),
 (108, np.float64(0.16222142113076252)),
 (1804, np.float64(0.16222142113076252)),
 (94, np.float64(0.15907119074394446)),
 (2511, np.float64(0.15907119074394446)),
 (52, np.float64(0.15789473684210528)),
 (1392, np.float64(0.15747244473304667)),
 (31, np.float64(0.15609763526361567)),
 (581, np.float64(0.15609763526361567)),
 (1295, np.float64(0.15585730003983933)),
 (1379, np.float64(0.15585730003983933)),
 (4336, np.float64(0.15389675281277312)),
 (91, np.float64(0.15328483487124145)),
 (168, np.float64(0.152008377581442)),
 (3626, np.float64(0.15061880828219448)),
 (311, np.float64(0.15018785229652765)),
 (1961, np.float64(0.14910501299480672)),
 (577, np.float64(0.14808721943977307)),
 (3352, np.float64(0.14808721943977307)),
 (158, np.float64(0.14673479641335554)),
 (502, np.float64(0.14673479641335554)),
 (111, np.float64(0.14567913668701626)),
 (2165, np.float64(0.14567913668701626)),
 (1353, np.float64(0.14509525002200235)),
 (172, np.float64(0.14509525002200233)),
 (490, np.float64(0.14509525002200233)),
 (17, np.float64(0.1442149876003076)),
 (1934, np.float64(0.14350946197048198)),
 (1176, np.float64(0.1433848336691011)),
 (422, np.float64(0.14159846508095775)),
 (505, np.float64(0.14159846508095775)),
 (1484, np.float64(0.14159846508095775)),
 (557, np.float64(0.1411956236812263)),
 (41, np.float64(0.1404878717372541)),
 (84, np.float64(0.13977653617040256)),
 (369, np.float64(0.1391037210186643)),
 (568, np.float64(0.1391037210186643)),
 (2682, np.float64(0.1391037210186643)),
 (56, np.float64(0.13834289277321493)),
 (249, np.float64(0.13834289277321493)),
 (1325, np.float64(0.13834289277321493)),
 (1320, np.float64(0.13764944032233709)),
 (332, np.float64(0.13710212427677043)),
 (1218, np.float64(0.13710212427677043)),
 (487, np.float64(0.13530201829834768)),
 (2580, np.float64(0.13530201829834768)),
 (3997, np.float64(0.13530201829834768)),
 (187, np.float64(0.13518451760896877)),
 (413, np.float64(0.13518451760896877)),
 (1669, np.float64(0.13497638119975428)),
 (4348, np.float64(0.13497638119975428)),
 (2129, np.float64(0.13369695534647594)),
 (2869, np.float64(0.13369695534647594)),
 (1941, np.float64(0.13334518676566626)),
 (2616, np.float64(0.1324532357065044)),
 (2968, np.float64(0.1324532357065044)),
 (4490, np.float64(0.1324532357065044)),
 (595, np.float64(0.13157894736842107)),
 (1013, np.float64(0.13157894736842107)),
 (1297, np.float64(0.13157894736842107)),
 (3407, np.float64(0.13157894736842107)),
 (3620, np.float64(0.13157894736842107)),
 (127, np.float64(0.13112201362143713)),
 (342, np.float64(0.1302565123238377)),
 (2476, np.float64(0.130066495428618)),
 (754, np.float64(0.12988108336653278)),
 (1475, np.float64(0.12988108336653278)),
 (68, np.float64(0.12977713690461004)),
 (134, np.float64(0.12977713690461004)),
 (368, np.float64(0.12977713690461004)),
 (1156, np.float64(0.12977713690461004)),
 (1000, np.float64(0.12892051277806202)),
 (3671, np.float64(0.12824729401064427)),
 (1045, np.float64(0.12725695259515557)),
 (1094, np.float64(0.12725695259515557)),
 (1743, np.float64(0.12725695259515557)),
 (2374, np.float64(0.12725695259515557)),
 (3374, np.float64(0.12725695259515557)),
 (740, np.float64(0.126673647984535)),
 (1613, np.float64(0.126673647984535)),
 (1571, np.float64(0.12565617248750865)),
 (1711, np.float64(0.12565617248750865)),
 (529, np.float64(0.12515654358043973)),
 (778, np.float64(0.12515654358043973)),
 (483, np.float64(0.12487810821089254)),
 (1654, np.float64(0.12487810821089254)),
 (420, np.float64(0.12369267399882337)),
 (1035, np.float64(0.12369267399882337)),
 (3441, np.float64(0.12369267399882337)),
 (1829, np.float64(0.12262786789699316)),
 (4673, np.float64(0.12262786789699316)),
 (939, np.float64(0.12262786789699313)),
 (1737, np.float64(0.12262786789699313)),
 (228, np.float64(0.12227899701112963)),
 (279, np.float64(0.12227899701112963)),
 (2709, np.float64(0.12227899701112963)),
 (3307, np.float64(0.12227899701112963)),
 (3405, np.float64(0.12227899701112963)),
 (3216, np.float64(0.12166606584807191)),
 (278, np.float64(0.12091270835166862)),
 (432, np.float64(0.12091270835166862)),
 (549, np.float64(0.12091270835166862)),
 (28, np.float64(0.1204950466257556)),
 (1272, np.float64(0.1204950466257556)),
 (2071, np.float64(0.1204950466257556)),
 (238, np.float64(0.11980845957463077)),
 (95, np.float64(0.11959121830873498)),
 (454, np.float64(0.11959121830873498)),
 (72, np.float64(0.11846977555181847)),
 (275, np.float64(0.11846977555181847)),
 (579, np.float64(0.11846977555181847)),
 (2864, np.float64(0.11846977555181847)),
 (123, np.float64(0.11831213107007527)),
 (1508, np.float64(0.11831213107007527)),
 (2543, np.float64(0.11831213107007527)),
 (653, np.float64(0.11803342130469505)),
 (808, np.float64(0.11803342130469505)),
 (3145, np.float64(0.11803342130469505)),
 (4201, np.float64(0.11803342130469505)),
 (50, np.float64(0.116543309349613)),
 (1978, np.float64(0.116543309349613)),
 (692, np.float64(0.11587244366483038)),
 (1275, np.float64(0.11587244366483038)),
 (3628, np.float64(0.11587244366483038)),
 (169, np.float64(0.1147078669352809)),
 (624, np.float64(0.1147078669352809)),
 (166, np.float64(0.11470786693528087)),
 (232, np.float64(0.11470786693528087)),
 (294, np.float64(0.11470786693528087)),
 (859, np.float64(0.11470786693528087)),
 (1612, np.float64(0.11470786693528087)),
 (1570, np.float64(0.1139194873735864)),
 (5, np.float64(0.11357771260606365)),
 (199, np.float64(0.11357771260606365)),
 (206, np.float64(0.11357771260606365)),
 (10, np.float64(0.11295649894498103)),
 (87, np.float64(0.11295649894498103)),
 (513, np.float64(0.11295649894498103)),
 (687, np.float64(0.11295649894498103)),
 (1029, np.float64(0.11295649894498103)),
 (3006, np.float64(0.11295649894498103)),
 (81, np.float64(0.11239029738980326)),
 (627, np.float64(0.11164843913471803)),
 (1299, np.float64(0.11164843913471803)),
 (1369, np.float64(0.11164843913471803)),
 (1723, np.float64(0.11164843913471803)),
 (2255, np.float64(0.11164843913471803)),
 (2319, np.float64(0.11164843913471803)),
 (3719, np.float64(0.11164843913471803)),
 (3998, np.float64(0.11164843913471803)),
 (126, np.float64(0.11128297681493143)),
 (508, np.float64(0.11128297681493143)),
 (2446, np.float64(0.11128297681493143)),
 (2579, np.float64(0.11128297681493143)),
 (777, np.float64(0.11037769642208699)),
 (14, np.float64(0.10968169942141635)),
 (854, np.float64(0.10968169942141635)),
 (900, np.float64(0.10968169942141635)),
 (1193, np.float64(0.10968169942141635)),
 (3496, np.float64(0.10968169942141635)),
 (141, np.float64(0.10882143751650175)),
 (1520, np.float64(0.10882143751650175)),
 (1717, np.float64(0.10882143751650175)),
 (2630, np.float64(0.10882143751650175)),
 (3659, np.float64(0.10882143751650175)),
 (4016, np.float64(0.10882143751650175)),
 (4133, np.float64(0.10882143751650175)),
 (1017, np.float64(0.10838874619051501)),
 (1493, np.float64(0.10838874619051501)),
 (2102, np.float64(0.10838874619051501)),
 (2435, np.float64(0.10838874619051501)),
 (2756, np.float64(0.10838874619051501)),
 (312, np.float64(0.10814761408717502)),
 (1080, np.float64(0.10814761408717502)),
 (1292, np.float64(0.10814761408717502)),
 (2009, np.float64(0.10814761408717502)),
 (3338, np.float64(0.10814761408717502)),
 (3618, np.float64(0.10814761408717502)),
 (4095, np.float64(0.10814761408717502)),
 (18, np.float64(0.10743376064838502)),
 (102, np.float64(0.10743376064838502)),
 (131, np.float64(0.106676149412533)),
 (174, np.float64(0.106676149412533)),
 (266, np.float64(0.106676149412533)),
 (2068, np.float64(0.106676149412533)),
 (239, np.float64(0.10650358071057624)),
 (403, np.float64(0.10650358071057624)),
 (233, np.float64(0.10619884881071831)),
 (325, np.float64(0.10619884881071831)),
 (773, np.float64(0.10619884881071831)),
 (1154, np.float64(0.10619884881071831)),
 (3053, np.float64(0.10619884881071831)),
 (3779, np.float64(0.10619884881071831)),
 (3837, np.float64(0.10619884881071831)),
 (3952, np.float64(0.10619884881071831)),
 (295, np.float64(0.10526315789473685)),
 (330, np.float64(0.10526315789473685)),
 (535, np.float64(0.10526315789473685)),
 (986, np.float64(0.10526315789473685)),
 (1271, np.float64(0.10526315789473685)),
 (2177, np.float64(0.10526315789473685)),
 (3100, np.float64(0.10526315789473685)),
 (4077, np.float64(0.10526315789473685)),
 (4228, np.float64(0.10526315789473685)),
 (182, np.float64(0.10390486669322622)),
 (139, np.float64(0.10385162309931599)),
 (105, np.float64(0.1037571695799112)),
 (476, np.float64(0.1037571695799112)),
 (2452, np.float64(0.1037571695799112)),
 (2558, np.float64(0.1037571695799112)),
 (2758, np.float64(0.1037571695799112)),
 (4196, np.float64(0.1037571695799112)),
 (4545, np.float64(0.10301070542879115)),
 (334, np.float64(0.10259783520851541)),
 (643, np.float64(0.10259783520851541)),
 (1054, np.float64(0.10259783520851541)),
 (3781, np.float64(0.10259783520851541)),
 (85, np.float64(0.10203255357771539)),
 (33, np.float64(0.10147651372376076)),
 (148, np.float64(0.10147651372376076)),
 (157, np.float64(0.10147651372376076)),
 (263, np.float64(0.10147651372376076)),
 (715, np.float64(0.10147651372376076)),
 (935, np.float64(0.10147651372376076)),
 (1278, np.float64(0.10147651372376076)),
 (1497, np.float64(0.10147651372376076)),
 (2517, np.float64(0.10147651372376076)),
 (2656, np.float64(0.10147651372376076)),
 (4331, np.float64(0.10147651372376076)),
 (129, np.float64(0.101338918387628)),
 (510, np.float64(0.101338918387628)),
 (898, np.float64(0.101338918387628)),
 (1084, np.float64(0.101338918387628)),
 (1107, np.float64(0.101338918387628)),
 (3462, np.float64(0.101338918387628)),
 (307, np.float64(0.1003911722115382)),
 (587, np.float64(0.10012523486435178)),
 (1231, np.float64(0.10012523486435178)),
 (4043, np.float64(0.10012523486435178)),
 (35, np.float64(0.09933992677987831)),
 (400, np.float64(0.09933992677987831)),
 (660, np.float64(0.09933992677987831)),
 (781, np.float64(0.09933992677987831)),
 (1938, np.float64(0.09933992677987831)),
 (2657, np.float64(0.09933992677987831)),
 (4254, np.float64(0.09933992677987831)),
 (4623, np.float64(0.09933992677987831)),
 (371, np.float64(0.0989541391990587)),
 (412, np.float64(0.0989541391990587)),
 (473, np.float64(0.0989541391990587)),
 (870, np.float64(0.0989541391990587)),
 (1200, np.float64(0.0989541391990587)),
 (1435, np.float64(0.0989541391990587)),
 (2592, np.float64(0.0989541391990587)),
 (270, np.float64(0.0978231976089037)),
 (410, np.float64(0.0978231976089037)),
 (813, np.float64(0.0978231976089037)),
 (933, np.float64(0.0978231976089037)),
 (1274, np.float64(0.0978231976089037)),
 (1819, np.float64(0.0978231976089037)),
 (1842, np.float64(0.0978231976089037)),
 (2280, np.float64(0.0978231976089037)),
 (292, np.float64(0.09733285267845754)),
 (389, np.float64(0.09733285267845754)),
 (530, np.float64(0.09733285267845754)),
 (691, np.float64(0.09733285267845754)),
 (791, np.float64(0.09733285267845754)),
 (920, np.float64(0.09733285267845754)),
 (1075, np.float64(0.09733285267845754)),
 (2647, np.float64(0.09733285267845754)),
 (3091, np.float64(0.09733285267845754)),
 (3734, np.float64(0.09733285267845754)),
 (1087, np.float64(0.09694584179118516)),
 (1999, np.float64(0.0967301666813349)),
 (243, np.float64(0.09567297464698798)),
 (785, np.float64(0.09558988911273408)),
 (122, np.float64(0.09544271444636668)),
 (564, np.float64(0.09544271444636668)),
 (1404, np.float64(0.09544271444636668)),
 (1470, np.float64(0.09544271444636668)),
 (1585, np.float64(0.09544271444636668)),
 (1682, np.float64(0.09544271444636668)),
 (1752, np.float64(0.09544271444636668)),
 (589, np.float64(0.09464970485606021)),
 (618, np.float64(0.09464970485606021)),
 (1355, np.float64(0.09464970485606021)),
 (12, np.float64(0.09365858115816941)),
 (23, np.float64(0.09365858115816941)),
 (43, np.float64(0.09365858115816941)),
 (142, np.float64(0.09365858115816941)),
 (236, np.float64(0.09365858115816941)),
 (362, np.float64(0.09365858115816941)),
 (2089, np.float64(0.09365858115816941)),
 (2392, np.float64(0.09365858115816941)),
 (2648, np.float64(0.09365858115816941)),
 (2792, np.float64(0.09365858115816941)),
 (160, np.float64(0.09304036594559835)),
 (596, np.float64(0.09269795493186431)),
 (1414, np.float64(0.09269795493186431)),
 (2484, np.float64(0.09269795493186431)),
 (511, np.float64(0.09197090092274487)),
 (922, np.float64(0.09197090092274487)),
 (1025, np.float64(0.09197090092274487)),
 (1304, np.float64(0.09197090092274487)),
 (2813, np.float64(0.09197090092274487)),
 (2836, np.float64(0.09197090092274487)),
 (3426, np.float64(0.09197090092274487)),
 (479, np.float64(0.09183979479633063)),
 (1828, np.float64(0.09176629354822471)),
 (1920, np.float64(0.09176629354822471)),
 (1276, np.float64(0.09086217008485092)),
 (1492, np.float64(0.09086217008485092)),
 (112, np.float64(0.09037128496931669)),
 (164, np.float64(0.09037128496931669)),
 (242, np.float64(0.09037128496931669)),
 (794, np.float64(0.09037128496931669)),
 (960, np.float64(0.09037128496931669)),
 (978, np.float64(0.09037128496931669)),
 (1002, np.float64(0.09037128496931669)),
 (1247, np.float64(0.09037128496931669)),
 (4468, np.float64(0.09037128496931669)),
 (799, np.float64(0.09012301173931252)),
 (2270, np.float64(0.08998425413316952)),
 (2384, np.float64(0.08998425413316952)),
 (2852, np.float64(0.08998425413316952)),
 (3152, np.float64(0.08998425413316952)),
 (4353, np.float64(0.08998425413316952)),
 (4502, np.float64(0.08998425413316952)),
 (4516, np.float64(0.08998425413316952)),
 (4654, np.float64(0.08998425413316952)),
 (2966, np.float64(0.0891313035643173)),
 (2444, np.float64(0.08903057122447033)),
 (21, np.float64(0.08885233166386385)),
 (227, np.float64(0.08885233166386385)),
 (306, np.float64(0.08885233166386385)),
 (349, np.float64(0.08885233166386385)),
 (356, np.float64(0.08885233166386385)),
 (775, np.float64(0.08885233166386385)),
 (901, np.float64(0.08885233166386385)),
 (1374, np.float64(0.08885233166386385)),
 (1696, np.float64(0.08885233166386385)),
 (1786, np.float64(0.08885233166386385)),
 (2163, np.float64(0.08885233166386385)),
 (3535, np.float64(0.08885233166386385)),
 (3814, np.float64(0.08885233166386385)),
 (4626, np.float64(0.08885233166386385)),
 (63, np.float64(0.08830215713766959)),
 (107, np.float64(0.08830215713766959)),
 (170, np.float64(0.08830215713766959)),
 (363, np.float64(0.08830215713766959)),
 (541, np.float64(0.08830215713766959)),
 (812, np.float64(0.08830215713766959)),
 (2001, np.float64(0.08830215713766959)),
 (32, np.float64(0.08749572785196143)),
 (45, np.float64(0.08749572785196143)),
 (222, np.float64(0.08749572785196143)),
 (467, np.float64(0.08749572785196143)),
 (1, np.float64(0.08740748201220976)),
 (75, np.float64(0.08740748201220976)),
 (88, np.float64(0.08740748201220976)),
 (121, np.float64(0.08740748201220976)),
 (245, np.float64(0.08740748201220976)),
 (315, np.float64(0.08740748201220976)),
 (626, np.float64(0.08740748201220976)),
 (786, np.float64(0.08740748201220976)),
 (894, np.float64(0.08740748201220976)),
 (937, np.float64(0.08740748201220976)),
 (3299, np.float64(0.08740748201220976)),
 (3447, np.float64(0.08740748201220976)),
 (230, np.float64(0.08671099695241201)),
 (381, np.float64(0.08671099695241201)),
 (1137, np.float64(0.08671099695241201)),
 (2494, np.float64(0.08671099695241201)),
 (2876, np.float64(0.08671099695241201)),
 (4163, np.float64(0.08671099695241201)),
 (4737, np.float64(0.08671099695241201)),
 (2382, np.float64(0.08646430798325933)),
 (86, np.float64(0.08603090020146065)),
 (96, np.float64(0.08603090020146065)),
 (814, np.float64(0.08603090020146065)),
 (1111, np.float64(0.08603090020146065)),
 (1140, np.float64(0.08603090020146065)),
 (1267, np.float64(0.08603090020146065)),
 (2243, np.float64(0.08603090020146065)),
 (2247, np.float64(0.08603090020146065)),
 (2790, np.float64(0.08603090020146065)),
 (3089, np.float64(0.08603090020146065)),
 (4257, np.float64(0.08603090020146065)),
 (4657, np.float64(0.08603090020146065)),
 (654, np.float64(0.08594700851870801)),
 (1280, np.float64(0.08594700851870801)),
 (1874, np.float64(0.08594700851870801)),
 (103, np.float64(0.08520286456846099)),
 (39, np.float64(0.08471737420873576)),
 (101, np.float64(0.08471737420873576)),
 (203, np.float64(0.08471737420873576)),
 (457, np.float64(0.08471737420873576)),
 (547, np.float64(0.08471737420873576)),
 (899, np.float64(0.08471737420873576)),
 (1205, np.float64(0.08471737420873576)),
 (1469, np.float64(0.08471737420873576)),
 (1519, np.float64(0.08471737420873576)),
 (2300, np.float64(0.08471737420873576)),
 (3233, np.float64(0.08471737420873576)),
 (3908, np.float64(0.08471737420873576)),
 (193, np.float64(0.08447772061910234)),
 (491, np.float64(0.08447772061910234)),
 (501, np.float64(0.08447772061910234)),
 (1824, np.float64(0.08447772061910234)),
 (3439, np.float64(0.08447772061910234)),
 (1401, np.float64(0.0837707816583391)),
 (1617, np.float64(0.0837707816583391)),
 (2246, np.float64(0.0837707816583391)),
 (2335, np.float64(0.0837707816583391)),
 (3067, np.float64(0.0837707816583391)),
 (4492, np.float64(0.0837707816583391)),
 (4718, np.float64(0.0837707816583391)),
 (257, np.float64(0.08346223261119858)),
 (634, np.float64(0.08346223261119858)),
 (746, np.float64(0.08346223261119858)),

# Recommend Function

In [50]:
def recommend(movie):
  movie_index = new_df[new_df['title'] ==  movie].index[0]
  distances = similarity[movie_index]
  distances = list(enumerate(distances))
  movies_list = sorted(distances, reverse=True, key=lambda x: x[1])[1:8]
  
  for i in movies_list:
    print(new_df.iloc[i[0]].title)

recommend('Batman')

Batman
Batman & Robin
The Dark Knight Rises
Batman Begins
Batman Returns
Batman Forever
The Dark Knight

In [51]:
new_df.iloc[1192]

movie_id                                                11551
title                                          Small Soldiers
tags        when missil technolog is use to enhanc toy act...
Name: 1192, dtype: object

In [ ]:
import pickle
pickle.dump(new_df,open('movies.pkl','wb'))

In [ ]:
pickle.dump(similarity,open('similarity_file.pkl','wb'))